-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 00:40:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Kookbob
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Kookbob
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kookbob` DEFAULT CHARACTER SET utf8 ;
USE `Kookbob` ;

-- -----------------------------------------------------
-- Table `Kookbob`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kookbob`.`restaurant` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Kookbob`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kookbob`.`menu` (
  `menu_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `menu_name` VARCHAR(45) NOT NULL,
  `count_review` INT(11) NOT NULL DEFAULT '0',
  `star_avg` FLOAT NOT NULL DEFAULT '0',
  `total_like` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`menu_Id`),
  INDEX `restaurant_link_idx` (`restaurant_name` ASC) VISIBLE,
  CONSTRAINT `restaurant_link`
    FOREIGN KEY (`restaurant_name`)
    REFERENCES `Kookbob`.`restaurant` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 24850
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Kookbob`.`menu_appearance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kookbob`.`menu_appearance` (
  `menu_appearance_id` INT(11) NOT NULL AUTO_INCREMENT,
  `menu_Id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `subMenu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`menu_appearance_id`),
  INDEX `fk_menu_appearance1` (`menu_Id` ASC) VISIBLE,
  CONSTRAINT `fk_menu_appearance1`
    FOREIGN KEY (`menu_Id`)
    REFERENCES `Kookbob`.`menu` (`menu_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25447
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Kookbob`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kookbob`.`user` (
  `user_id` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `writing_count` INT(11) NULL DEFAULT NULL,
  `user_num` INT(11) NOT NULL AUTO_INCREMENT,
  `E-mail` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_num_UNIQUE` (`user_num` ASC) VISIBLE,
  UNIQUE INDEX `E-mail_UNIQUE` (`E-mail` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Kookbob`.`menu_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kookbob`.`menu_like` (
  `menu_like_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Mliked_user_id` VARCHAR(45) NOT NULL,
  `Mliked_menu_id` INT(11) NOT NULL,
  PRIMARY KEY (`menu_like_id`),
  INDEX `fk_like_user1_idx` (`Mliked_user_id` ASC) VISIBLE,
  INDEX `fk_like_menu1_idx` (`Mliked_menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_menu1`
    FOREIGN KEY (`Mliked_menu_id`)
    REFERENCES `Kookbob`.`menu` (`menu_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_like_menu2`
    FOREIGN KEY (`Mliked_user_id`)
    REFERENCES `Kookbob`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Kookbob`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kookbob`.`review` (
  `review_number` INT(11) NOT NULL AUTO_INCREMENT,
  `review_user_id` VARCHAR(45) NULL DEFAULT NULL,
  `review_menu_id_reviewd` INT(11) NULL DEFAULT NULL,
  `menu_name` VARCHAR(45) NULL DEFAULT NULL,
  `write_date` DATETIME NULL DEFAULT NULL,
  `star` FLOAT NULL DEFAULT NULL,
  `review_like` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`review_number`),
  INDEX `fk_review_user_idx` (`review_user_id` ASC) VISIBLE,
  INDEX `fk_review_menu1_idx` (`review_menu_id_reviewd` ASC) VISIBLE,
  CONSTRAINT `fk_review_menu1`
    FOREIGN KEY (`review_menu_id_reviewd`)
    REFERENCES `Kookbob`.`menu` (`menu_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_review_menu2`
    FOREIGN KEY (`review_user_id`)
    REFERENCES `Kookbob`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 175
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Kookbob`.`review_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kookbob`.`review_like` (
  `review_like_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Rlike_user_id` VARCHAR(45) NOT NULL,
  `Rlike_review_no` INT(11) NOT NULL,
  PRIMARY KEY (`review_like_id`),
  INDEX `fk_reviewLike_user1_idx` (`Rlike_user_id` ASC) VISIBLE,
  INDEX `fk_reviewLike_review1_idx` (`Rlike_review_no` ASC) VISIBLE,
  CONSTRAINT `fk_review_like_review_id`
    FOREIGN KEY (`Rlike_review_no`)
    REFERENCES `Kookbob`.`review` (`review_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reviewlike_id`
    FOREIGN KEY (`Rlike_user_id`)
    REFERENCES `Kookbob`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
